### ISSUE TITLE
웹 프레임워크 / 데이터베이스 선택

### ISSUE THREAD

**Issue by surplus-dev** [Oriwiki/DuckPy#19]
## 프레임워크
 * 장고
 * 플라스크
 * Bottle

### SQL
 * MySQL
 * SQLite
 * PostgreSQL

### NoSQL
 * 몽고DB
 * 기타 등등

**Comment by Oriwiki** [comment]
지금은 웹프레임워크는 장고로, 데이터베이스는 MySQL로 생각하고 있습니다.

**Comment by surplus-dev** [comment]
흠 무난한 조합이군요 근데 MySQL 관련 툴이 자주 쓰이는 게 3개나 있더라고요 pymysql 부터 시작해서

**Comment by Oriwiki** [comment]
쿼리 처리는 장고 내부의 orm를 쓸 예정이고, 드라이버는 실제 장고 코드 만질 때 생각하는 걸로..ㅎ

**Comment by surplus-dev** [comment]
그러고보니 장고는 orm이 있었네요 늘 플라스크만 쓰다보니

**Comment by surplus-dev** [comment]
일단은 그렇게 정하는걸루
