### ISSUE TITLE
문서 기록

### ISSUE THREAD

**Issue by surplus-dev** [Oriwiki/DuckPy#30]
문서 이동 기록을 따로 테이블에 저장하게 해서 문서 이동의 흐름을 볼 수 있게 합시다

**Comment by Oriwiki** [comment]
log 테이블을 만들고 type 컬럼을 지정해서 사이트 전체 로그를 기록하는 것으로..

**Comment by surplus-dev** [comment]
괜찮네요

**Comment by Oriwiki** [comment]
* 문서 생성(0)
* 문서 수정(1)
* 문서 이동(2)
* ACL 변동(3)
* 문서 삭제(4)

**Comment by Oriwiki** [comment]
Revision에서 작성하면 되므로 굳이 문서 Log 테이블을 만들 이유는 없네요.

회원 차단 Log쪽만 기록하면 될 듯합니다.
