### ISSUE TITLE
이름공간

### ISSUE THREAD

**Issue by Oriwiki** [Oriwiki/DuckPy#31]
* 일반(0)
* 시스템(1)
* 사용자(2)
* 파일(3)
* 분류(4)

**Comment by ddarkr** [comment]
미디어위키처럼 위키별 이름공간도 있었으면...

**Comment by Oriwiki** [comment]
ddarkr// 아 그걸 깜빡했네요 ^^;
* 프로젝트(5)

**Comment by Oriwiki** [comment]
* 틀(6)
